export const PERMISSIONS = [
  'USERS_VIEW',
  'USERS_VIEW_SELF',
  'USERS_CREATE',
  'USERS_UPDATE',
  'USERS_UPDATE_SELF',
  'USERS_DELETE',
  'USERS_LOCK',
  'USERS_UNLOCK',
  'USERS_TAGS_MANAGE',
  'USERS_FAMILY_LINK',
  'USERS_UPLOAD_AVATAR',
  'USERS_UPLOAD_AVATAR_SELF',
  'HOUSEHOLD_CLASSIFICATIONS_VIEW',
  'HOUSEHOLD_CLASSIFICATIONS_MANAGE',
  'AUTH_VIEW_SELF',
  'AUTH_MANAGE_SESSIONS',
  'AUTH_CHANGE_PASSWORD',
  'SYSTEM_ANALYTICS_VIEW',
  'CONFESSIONS_VIEW',
  'CONFESSIONS_CREATE',
  'CONFESSIONS_ASSIGN_USER',
  'CONFESSIONS_SESSION_TYPES_MANAGE',
  'CONFESSIONS_ALERTS_VIEW',
  'CONFESSIONS_ALERTS_MANAGE',
  'CONFESSIONS_ANALYTICS_VIEW',
  'PASTORAL_VISITATIONS_VIEW',
  'PASTORAL_VISITATIONS_CREATE',
  'PASTORAL_VISITATIONS_ANALYTICS_VIEW',
  'SECTORS_VIEW',
  'SECTORS_CREATE',
  'SECTORS_UPDATE',
  'SECTORS_DELETE',
  'MEETINGS_VIEW',
  'MEETINGS_VIEW_OWN',
  'MEETINGS_CREATE',
  'MEETINGS_UPDATE',
  'MEETINGS_DELETE',
  'MEETINGS_SERVANTS_MANAGE',
  'MEETINGS_COMMITTEES_MANAGE',
  'MEETINGS_ACTIVITIES_MANAGE',
  'MEETINGS_RESPONSIBILITIES_VIEW',
  'MEETINGS_SERVANT_HISTORY_VIEW',
  'MEETINGS_MEMBERS_VIEW',
  'MEETINGS_ATTENDANCE_MANAGE',
  'MEETINGS_DOCUMENTATION_MANAGE',
  'MEETINGS_SETTINGS_MANAGE',
  'MEETINGS_MEMBERS_NOTES_UPDATE',
  'DIVINE_LITURGIES_VIEW',
  'DIVINE_LITURGIES_MANAGE',
  'DIVINE_LITURGIES_ATTENDANCE_MANAGE',
  'DIVINE_LITURGIES_ATTENDANCE_MANAGE_ASSIGNED_USERS',
  'DIVINE_LITURGIES_PRIESTS_MANAGE',
  'ARCHIVE_VIEW',
  'ARCHIVE_UPLOAD',
  'ARCHIVE_COLLECTIONS_MANAGE',
  'ARCHIVE_STORIES_MANAGE',
  'ARCHIVE_HONOREES_MANAGE',
  'ARCHIVE_PUBLISH',
  'LANDING_CONTENT_MANAGE',
  'NOTIFICATIONS_VIEW',
  'NOTIFICATIONS_CREATE',
  'NOTIFICATIONS_UPDATE',
  'NOTIFICATIONS_TYPES_MANAGE',
  'NOTIFICATIONS_TEMPLATES_MANAGE',
  'CHATS_VIEW',
  'CHATS_START',
  'CHATS_SEND',
  'CHATS_GROUPS_MANAGE',
  'CHATS_BROADCAST',
  'CHATS_VIEW_ALL',
  'BOOKINGS_VIEW_OWN',
  'BOOKINGS_VIEW',
  'BOOKINGS_MANAGE',
  'BOOKINGS_TYPES_MANAGE',
];

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: [...PERMISSIONS],
  ADMIN: [
    'USERS_VIEW',
    'USERS_VIEW_SELF',
    'USERS_CREATE',
    'USERS_UPDATE',
    'USERS_UPDATE_SELF',
    'USERS_DELETE',
    'USERS_LOCK',
    'USERS_UNLOCK',
    'USERS_TAGS_MANAGE',
    'USERS_FAMILY_LINK',
    'USERS_UPLOAD_AVATAR',
    'USERS_UPLOAD_AVATAR_SELF',
    'HOUSEHOLD_CLASSIFICATIONS_VIEW',
    'AUTH_VIEW_SELF',
    'AUTH_CHANGE_PASSWORD',
    'CONFESSIONS_VIEW',
    'CONFESSIONS_CREATE',
    'CONFESSIONS_ASSIGN_USER',
    'CONFESSIONS_SESSION_TYPES_MANAGE',
    'CONFESSIONS_ALERTS_VIEW',
    'CONFESSIONS_ALERTS_MANAGE',
    'CONFESSIONS_ANALYTICS_VIEW',
    'PASTORAL_VISITATIONS_VIEW',
    'PASTORAL_VISITATIONS_CREATE',
    'PASTORAL_VISITATIONS_ANALYTICS_VIEW',
    'SECTORS_VIEW',
    'SECTORS_CREATE',
    'SECTORS_UPDATE',
    'SECTORS_DELETE',
    'MEETINGS_VIEW',
    'MEETINGS_VIEW_OWN',
    'MEETINGS_CREATE',
    'MEETINGS_UPDATE',
    'MEETINGS_DELETE',
    'MEETINGS_SERVANTS_MANAGE',
    'MEETINGS_COMMITTEES_MANAGE',
    'MEETINGS_ACTIVITIES_MANAGE',
    'MEETINGS_RESPONSIBILITIES_VIEW',
    'MEETINGS_SERVANT_HISTORY_VIEW',
    'MEETINGS_MEMBERS_VIEW',
    'MEETINGS_ATTENDANCE_MANAGE',
    'MEETINGS_DOCUMENTATION_MANAGE',
    'MEETINGS_SETTINGS_MANAGE',
    'MEETINGS_MEMBERS_NOTES_UPDATE',
    'DIVINE_LITURGIES_VIEW',
    'DIVINE_LITURGIES_MANAGE',
    'ARCHIVE_VIEW',
    'ARCHIVE_UPLOAD',
    'ARCHIVE_COLLECTIONS_MANAGE',
    'ARCHIVE_STORIES_MANAGE',
    'ARCHIVE_HONOREES_MANAGE',
    'ARCHIVE_PUBLISH',
    'NOTIFICATIONS_VIEW',
    'NOTIFICATIONS_CREATE',
    'NOTIFICATIONS_UPDATE',
    'NOTIFICATIONS_TYPES_MANAGE',
    'CHATS_VIEW',
    'CHATS_SEND',
    'CHATS_GROUPS_MANAGE',
    'BOOKINGS_VIEW_OWN',
    'BOOKINGS_VIEW',
    'BOOKINGS_MANAGE',
    'BOOKINGS_TYPES_MANAGE',
  ],
  USER: [
    'AUTH_VIEW_SELF',
    'AUTH_CHANGE_PASSWORD',
    'USERS_VIEW_SELF',
    'USERS_UPDATE_SELF',
    'USERS_UPLOAD_AVATAR_SELF',
    'MEETINGS_VIEW_OWN',
    'MEETINGS_MEMBERS_VIEW',
    'MEETINGS_ATTENDANCE_MANAGE',
    'MEETINGS_DOCUMENTATION_MANAGE',
    'MEETINGS_MEMBERS_NOTES_UPDATE',
    'DIVINE_LITURGIES_VIEW',
    'ARCHIVE_VIEW',
    'BOOKINGS_VIEW_OWN',
    'NOTIFICATIONS_VIEW',
    'CHATS_VIEW',
    'CHATS_SEND',
  ],
};

export const SUPER_ADMIN_ONLY_PERMISSIONS = ['CHATS_START'];

export function filterAssignablePermissions(role, permissions = []) {
  const normalized = [...new Set(
    (Array.isArray(permissions) ? permissions : []).filter((permission) => PERMISSIONS.includes(permission))
  )];

  if (role === 'SUPER_ADMIN') {
    return normalized;
  }

  return normalized.filter((permission) => !SUPER_ADMIN_ONLY_PERMISSIONS.includes(permission));
}

export function canAssignPermissionToRole(role, permission) {
  return role === 'SUPER_ADMIN' || !SUPER_ADMIN_ONLY_PERMISSIONS.includes(permission);
}

export function computeEffectivePermissionsForRole(role, extraPermissions = [], deniedPermissions = []) {
  if (role === 'SUPER_ADMIN') {
    return [...PERMISSIONS];
  }

  const rolePermissions = ROLE_PERMISSIONS[role] || [];
  const effectiveSet = new Set([...rolePermissions, ...filterAssignablePermissions(role, extraPermissions)]);
  filterAssignablePermissions(role, deniedPermissions).forEach((permission) => effectiveSet.delete(permission));
  return [...effectiveSet];
}

export const PERMISSION_LABELS = {
  USERS_VIEW: 'View users',
  USERS_VIEW_SELF: 'View own profile',
  USERS_CREATE: 'Create users',
  USERS_UPDATE: 'Update users',
  USERS_UPDATE_SELF: 'Update own profile',
  USERS_DELETE: 'Delete users',
  USERS_LOCK: 'Lock accounts',
  USERS_UNLOCK: 'Unlock accounts',
  USERS_TAGS_MANAGE: 'Manage user tags',
  USERS_FAMILY_LINK: 'Manage family links',
  USERS_UPLOAD_AVATAR: 'Upload user avatars',
  USERS_UPLOAD_AVATAR_SELF: 'Upload own avatar',
  HOUSEHOLD_CLASSIFICATIONS_VIEW: 'View household classification results',
  HOUSEHOLD_CLASSIFICATIONS_MANAGE: 'Manage household classification rules',
  AUTH_VIEW_SELF: 'View own authentication profile',
  AUTH_MANAGE_SESSIONS: 'Manage sessions',
  AUTH_CHANGE_PASSWORD: 'Change password',
  SYSTEM_ANALYTICS_VIEW: 'View system analytics',
  CONFESSIONS_VIEW: 'View confessions',
  CONFESSIONS_CREATE: 'Create confession sessions',
  CONFESSIONS_ASSIGN_USER: 'Assign confession attendees',
  CONFESSIONS_SESSION_TYPES_MANAGE: 'Manage confession session types',
  CONFESSIONS_ALERTS_VIEW: 'View confession alerts',
  CONFESSIONS_ALERTS_MANAGE: 'Manage confession alerts',
  CONFESSIONS_ANALYTICS_VIEW: 'View confession analytics',
  PASTORAL_VISITATIONS_VIEW: 'View pastoral visitations',
  PASTORAL_VISITATIONS_CREATE: 'Create pastoral visitations',
  PASTORAL_VISITATIONS_ANALYTICS_VIEW: 'View pastoral visitation analytics',
  SECTORS_VIEW: 'View sectors',
  SECTORS_CREATE: 'Create sectors',
  SECTORS_UPDATE: 'Update sectors',
  SECTORS_DELETE: 'Delete sectors',
  MEETINGS_VIEW: 'View meetings',
  MEETINGS_VIEW_OWN: 'View own meetings',
  MEETINGS_CREATE: 'Create meetings',
  MEETINGS_UPDATE: 'Update meeting basics',
  MEETINGS_DELETE: 'Delete meetings',
  MEETINGS_SERVANTS_MANAGE: 'Manage meeting servants',
  MEETINGS_COMMITTEES_MANAGE: 'Manage meeting committees',
  MEETINGS_ACTIVITIES_MANAGE: 'Manage meeting activities',
  MEETINGS_RESPONSIBILITIES_VIEW: 'View servant responsibility suggestions',
  MEETINGS_SERVANT_HISTORY_VIEW: 'View servant meeting history',
  MEETINGS_MEMBERS_VIEW: 'View meeting members',
  MEETINGS_ATTENDANCE_MANAGE: 'Manage meeting attendance',
  MEETINGS_DOCUMENTATION_MANAGE: 'Manage daily meeting documentation',
  MEETINGS_SETTINGS_MANAGE: 'Manage meeting documentation settings',
  MEETINGS_MEMBERS_NOTES_UPDATE: 'Update meeting member notes',
  DIVINE_LITURGIES_VIEW: 'View divine liturgy schedules',
  DIVINE_LITURGIES_MANAGE: 'Manage divine liturgy schedules',
  DIVINE_LITURGIES_ATTENDANCE_MANAGE: 'Manage divine liturgy attendance',
  DIVINE_LITURGIES_ATTENDANCE_MANAGE_ASSIGNED_USERS: 'Manage divine liturgy attendance for assigned meeting users',
  DIVINE_LITURGIES_PRIESTS_MANAGE: 'Manage church priests list',
  ARCHIVE_VIEW: 'View archive workspace',
  ARCHIVE_UPLOAD: 'Upload archive photos',
  ARCHIVE_COLLECTIONS_MANAGE: 'Manage archive collections',
  ARCHIVE_STORIES_MANAGE: 'Manage archive stories',
  ARCHIVE_HONOREES_MANAGE: 'Manage honored people entries',
  ARCHIVE_PUBLISH: 'Publish archive items',
  LANDING_CONTENT_MANAGE: 'Manage landing page content',
  NOTIFICATIONS_VIEW: 'View notifications',
  NOTIFICATIONS_CREATE: 'Create notifications',
  NOTIFICATIONS_UPDATE: 'Update notifications',
  NOTIFICATIONS_TYPES_MANAGE: 'Manage notification types',
  NOTIFICATIONS_TEMPLATES_MANAGE: 'Manage notification templates',
  CHATS_VIEW: 'View chats',
  CHATS_START: 'Start chats',
  CHATS_SEND: 'Send chat messages',
  CHATS_GROUPS_MANAGE: 'Create and manage chat groups',
  CHATS_BROADCAST: 'Broadcast chat messages',
  CHATS_VIEW_ALL: 'View chats created by others when visibility allows it',
  BOOKINGS_VIEW_OWN: 'View own bookings',
  BOOKINGS_VIEW: 'View bookings',
  BOOKINGS_MANAGE: 'Manage bookings',
  BOOKINGS_TYPES_MANAGE: 'Manage booking types',
};

export const PERMISSION_GROUPS = [
  {
    id: 'users',
    label: 'User management',
    permissions: [
      'USERS_VIEW',
      'USERS_VIEW_SELF',
      'USERS_CREATE',
      'USERS_UPDATE',
      'USERS_UPDATE_SELF',
      'USERS_DELETE',
      'USERS_LOCK',
      'USERS_UNLOCK',
      'USERS_TAGS_MANAGE',
      'USERS_FAMILY_LINK',
      'USERS_UPLOAD_AVATAR',
      'USERS_UPLOAD_AVATAR_SELF',
      'HOUSEHOLD_CLASSIFICATIONS_VIEW',
      'HOUSEHOLD_CLASSIFICATIONS_MANAGE',
    ],
  },
  {
    id: 'auth',
    label: 'Authentication',
    permissions: [
      'AUTH_VIEW_SELF',
      'AUTH_MANAGE_SESSIONS',
      'AUTH_CHANGE_PASSWORD',
      'SYSTEM_ANALYTICS_VIEW',
    ],
  },
  {
    id: 'confessions',
    label: 'Confessions',
    permissions: [
      'CONFESSIONS_VIEW',
      'CONFESSIONS_CREATE',
      'CONFESSIONS_ASSIGN_USER',
      'CONFESSIONS_SESSION_TYPES_MANAGE',
      'CONFESSIONS_ALERTS_VIEW',
      'CONFESSIONS_ALERTS_MANAGE',
      'CONFESSIONS_ANALYTICS_VIEW',
    ],
  },
  {
    id: 'visitations',
    label: 'Pastoral visitations',
    permissions: [
      'PASTORAL_VISITATIONS_VIEW',
      'PASTORAL_VISITATIONS_CREATE',
      'PASTORAL_VISITATIONS_ANALYTICS_VIEW',
    ],
  },
  {
    id: 'divineLiturgies',
    label: 'Divine liturgies',
    permissions: [
      'DIVINE_LITURGIES_VIEW',
      'DIVINE_LITURGIES_MANAGE',
      'DIVINE_LITURGIES_ATTENDANCE_MANAGE',
      'DIVINE_LITURGIES_ATTENDANCE_MANAGE_ASSIGNED_USERS',
      'DIVINE_LITURGIES_PRIESTS_MANAGE',
    ],
  },
  {
    id: 'archive',
    label: 'Archive',
    permissions: [
      'ARCHIVE_VIEW',
      'ARCHIVE_UPLOAD',
      'ARCHIVE_COLLECTIONS_MANAGE',
      'ARCHIVE_STORIES_MANAGE',
      'ARCHIVE_HONOREES_MANAGE',
      'ARCHIVE_PUBLISH',
    ],
  },
  {
    id: 'publicSite',
    label: 'Public site',
    permissions: ['LANDING_CONTENT_MANAGE'],
  },
  {
    id: 'meetings',
    label: 'Sectors and meetings',
    permissions: [
      'SECTORS_VIEW',
      'SECTORS_CREATE',
      'SECTORS_UPDATE',
      'SECTORS_DELETE',
      'MEETINGS_VIEW',
      'MEETINGS_VIEW_OWN',
      'MEETINGS_CREATE',
      'MEETINGS_UPDATE',
      'MEETINGS_DELETE',
      'MEETINGS_SERVANTS_MANAGE',
      'MEETINGS_COMMITTEES_MANAGE',
      'MEETINGS_ACTIVITIES_MANAGE',
      'MEETINGS_RESPONSIBILITIES_VIEW',
      'MEETINGS_SERVANT_HISTORY_VIEW',
      'MEETINGS_MEMBERS_VIEW',
      'MEETINGS_ATTENDANCE_MANAGE',
      'MEETINGS_DOCUMENTATION_MANAGE',
      'MEETINGS_SETTINGS_MANAGE',
      'MEETINGS_MEMBERS_NOTES_UPDATE',
    ],
  },
  {
    id: 'notifications',
    label: 'Notifications',
    permissions: [
      'NOTIFICATIONS_VIEW',
      'NOTIFICATIONS_CREATE',
      'NOTIFICATIONS_UPDATE',
      'NOTIFICATIONS_TYPES_MANAGE',
      'NOTIFICATIONS_TEMPLATES_MANAGE',
    ],
  },
  {
    id: 'chats',
    label: 'Chats',
    permissions: [
      'CHATS_VIEW',
      'CHATS_START',
      'CHATS_SEND',
      'CHATS_GROUPS_MANAGE',
      'CHATS_BROADCAST',
      'CHATS_VIEW_ALL',
    ],
  },
  {
    id: 'bookings',
    label: 'Bookings',
    permissions: [
      'BOOKINGS_VIEW_OWN',
      'BOOKINGS_VIEW',
      'BOOKINGS_MANAGE',
      'BOOKINGS_TYPES_MANAGE',
    ],
  },
];
